services:
  nginx:
    build: .
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ${SSL_CERTIFICATE_KEY_FILE:-/dev/null}
        target: /etc/ssl/server.key
        read_only: true
      - type: bind
        source: ${SSL_CERTIFICATE_FILE:-/dev/null}
        target: /etc/ssl/server.crt
        read_only: true
